import React, { useContext } from "react";
import Head from "next/head";
import Header from "@/components/header";
import NFTMint from "./NFTMint";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Art Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="project description"
          content="Art NFT marketplace based on ethereum blockchain"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className="min-h-screen overflow-hidden">
        <Header />
        <NFTMint />
      </main>
    </React.Fragment>
  )
}
